//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace string_reverse_app.string_reverse_service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mindtree.com/StringReverseService", ConfigurationName="string_reverse_service.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name str from namespace http://mindtree.com/StringReverseService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://mindtree.com/StringReverseService/StringReverseMethod", ReplyAction="*")]
        string_reverse_app.string_reverse_service.StringReverseMethodResponse StringReverseMethod(string_reverse_app.string_reverse_service.StringReverseMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mindtree.com/StringReverseService/StringReverseMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<string_reverse_app.string_reverse_service.StringReverseMethodResponse> StringReverseMethodAsync(string_reverse_app.string_reverse_service.StringReverseMethodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StringReverseMethodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StringReverseMethod", Namespace="http://mindtree.com/StringReverseService", Order=0)]
        public string_reverse_app.string_reverse_service.StringReverseMethodRequestBody Body;
        
        public StringReverseMethodRequest() {
        }
        
        public StringReverseMethodRequest(string_reverse_app.string_reverse_service.StringReverseMethodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mindtree.com/StringReverseService")]
    public partial class StringReverseMethodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public StringReverseMethodRequestBody() {
        }
        
        public StringReverseMethodRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StringReverseMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StringReverseMethodResponse", Namespace="http://mindtree.com/StringReverseService", Order=0)]
        public string_reverse_app.string_reverse_service.StringReverseMethodResponseBody Body;
        
        public StringReverseMethodResponse() {
        }
        
        public StringReverseMethodResponse(string_reverse_app.string_reverse_service.StringReverseMethodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://mindtree.com/StringReverseService")]
    public partial class StringReverseMethodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StringReverseMethodResult;
        
        public StringReverseMethodResponseBody() {
        }
        
        public StringReverseMethodResponseBody(string StringReverseMethodResult) {
            this.StringReverseMethodResult = StringReverseMethodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : string_reverse_app.string_reverse_service.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<string_reverse_app.string_reverse_service.WebService1Soap>, string_reverse_app.string_reverse_service.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string_reverse_app.string_reverse_service.StringReverseMethodResponse string_reverse_app.string_reverse_service.WebService1Soap.StringReverseMethod(string_reverse_app.string_reverse_service.StringReverseMethodRequest request) {
            return base.Channel.StringReverseMethod(request);
        }
        
        public string StringReverseMethod(string str) {
            string_reverse_app.string_reverse_service.StringReverseMethodRequest inValue = new string_reverse_app.string_reverse_service.StringReverseMethodRequest();
            inValue.Body = new string_reverse_app.string_reverse_service.StringReverseMethodRequestBody();
            inValue.Body.str = str;
            string_reverse_app.string_reverse_service.StringReverseMethodResponse retVal = ((string_reverse_app.string_reverse_service.WebService1Soap)(this)).StringReverseMethod(inValue);
            return retVal.Body.StringReverseMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<string_reverse_app.string_reverse_service.StringReverseMethodResponse> string_reverse_app.string_reverse_service.WebService1Soap.StringReverseMethodAsync(string_reverse_app.string_reverse_service.StringReverseMethodRequest request) {
            return base.Channel.StringReverseMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<string_reverse_app.string_reverse_service.StringReverseMethodResponse> StringReverseMethodAsync(string str) {
            string_reverse_app.string_reverse_service.StringReverseMethodRequest inValue = new string_reverse_app.string_reverse_service.StringReverseMethodRequest();
            inValue.Body = new string_reverse_app.string_reverse_service.StringReverseMethodRequestBody();
            inValue.Body.str = str;
            return ((string_reverse_app.string_reverse_service.WebService1Soap)(this)).StringReverseMethodAsync(inValue);
        }
    }
}
