#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="M1037727")]
	public partial class linqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertemployee(employee instance);
    partial void Updateemployee(employee instance);
    partial void Deleteemployee(employee instance);
    partial void Insertmatch(match instance);
    partial void Updatematch(match instance);
    partial void Deletematch(match instance);
    #endregion
		
		public linqDataContext() : 
				base(global::sample.Properties.Settings.Default.M1037727ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<employee> employees
		{
			get
			{
				return this.GetTable<employee>();
			}
		}
		
		public System.Data.Linq.Table<match> matches
		{
			get
			{
				return this.GetTable<match>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.employee")]
	public partial class employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _emp_name;
		
		private int _emp_id;
		
		private string _designation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onemp_nameChanging(string value);
    partial void Onemp_nameChanged();
    partial void Onemp_idChanging(int value);
    partial void Onemp_idChanged();
    partial void OndesignationChanging(string value);
    partial void OndesignationChanged();
    #endregion
		
		public employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_name", DbType="VarChar(20)")]
		public string emp_name
		{
			get
			{
				return this._emp_name;
			}
			set
			{
				if ((this._emp_name != value))
				{
					this.Onemp_nameChanging(value);
					this.SendPropertyChanging();
					this._emp_name = value;
					this.SendPropertyChanged("emp_name");
					this.Onemp_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int emp_id
		{
			get
			{
				return this._emp_id;
			}
			set
			{
				if ((this._emp_id != value))
				{
					this.Onemp_idChanging(value);
					this.SendPropertyChanging();
					this._emp_id = value;
					this.SendPropertyChanged("emp_id");
					this.Onemp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_designation", DbType="VarChar(20)")]
		public string designation
		{
			get
			{
				return this._designation;
			}
			set
			{
				if ((this._designation != value))
				{
					this.OndesignationChanging(value);
					this.SendPropertyChanging();
					this._designation = value;
					this.SendPropertyChanged("designation");
					this.OndesignationChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.matches")]
	public partial class match : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _match_id;
		
		private System.DateTime _match_date;
		
		private string _first_team_name;
		
		private string _second_team_name;
		
		private int _first_team_goals;
		
		private int _second_team_goals;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmatch_idChanging(int value);
    partial void Onmatch_idChanged();
    partial void Onmatch_dateChanging(System.DateTime value);
    partial void Onmatch_dateChanged();
    partial void Onfirst_team_nameChanging(string value);
    partial void Onfirst_team_nameChanged();
    partial void Onsecond_team_nameChanging(string value);
    partial void Onsecond_team_nameChanged();
    partial void Onfirst_team_goalsChanging(int value);
    partial void Onfirst_team_goalsChanged();
    partial void Onsecond_team_goalsChanging(int value);
    partial void Onsecond_team_goalsChanged();
    #endregion
		
		public match()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_match_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int match_id
		{
			get
			{
				return this._match_id;
			}
			set
			{
				if ((this._match_id != value))
				{
					this.Onmatch_idChanging(value);
					this.SendPropertyChanging();
					this._match_id = value;
					this.SendPropertyChanged("match_id");
					this.Onmatch_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_match_date", DbType="Date NOT NULL")]
		public System.DateTime match_date
		{
			get
			{
				return this._match_date;
			}
			set
			{
				if ((this._match_date != value))
				{
					this.Onmatch_dateChanging(value);
					this.SendPropertyChanging();
					this._match_date = value;
					this.SendPropertyChanged("match_date");
					this.Onmatch_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_team_name", DbType="VarChar(20)")]
		public string first_team_name
		{
			get
			{
				return this._first_team_name;
			}
			set
			{
				if ((this._first_team_name != value))
				{
					this.Onfirst_team_nameChanging(value);
					this.SendPropertyChanging();
					this._first_team_name = value;
					this.SendPropertyChanged("first_team_name");
					this.Onfirst_team_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_second_team_name", DbType="VarChar(20)")]
		public string second_team_name
		{
			get
			{
				return this._second_team_name;
			}
			set
			{
				if ((this._second_team_name != value))
				{
					this.Onsecond_team_nameChanging(value);
					this.SendPropertyChanging();
					this._second_team_name = value;
					this.SendPropertyChanged("second_team_name");
					this.Onsecond_team_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_team_goals", DbType="Int NOT NULL")]
		public int first_team_goals
		{
			get
			{
				return this._first_team_goals;
			}
			set
			{
				if ((this._first_team_goals != value))
				{
					this.Onfirst_team_goalsChanging(value);
					this.SendPropertyChanging();
					this._first_team_goals = value;
					this.SendPropertyChanged("first_team_goals");
					this.Onfirst_team_goalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_second_team_goals", DbType="Int NOT NULL")]
		public int second_team_goals
		{
			get
			{
				return this._second_team_goals;
			}
			set
			{
				if ((this._second_team_goals != value))
				{
					this.Onsecond_team_goalsChanging(value);
					this.SendPropertyChanging();
					this._second_team_goals = value;
					this.SendPropertyChanged("second_team_goals");
					this.Onsecond_team_goalsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
