//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int BookingID { get; set; }
        public string MID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public int StatusID { get; set; }
        public int BookID { get; set; }
    
        public virtual BookDetail BookDetail { get; set; }
        public virtual BookingStatu BookingStatu { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
