#include<stdio.h>
#include<conio.h>
#include<string.h>
void main()
{
	student s1, s2, s3,s3,s;
	printf("\n enter the name of the student");
	gets(s1.n);
	printf("\n enter the rno");
	scanf("%d", &s1.rno);
	printf("\nenter the marks obtained in physics\n");
	scanf("%d", &s1.m1);
	printf("\nenter the marks obtained in chemistry\n");
	scanf("%d", &s1.m2);
	printf("\nenter the marks obtained in maths\n");
	scanf("%d", &s1.m3);
	printf("\nenter the marks obtained in english\n");
	scanf("%d", &s1.m4);
	printf("\nenter the marks obtained in cs\n");
	scanf("%d", &s1.m5);
	printf("\n enter the name of the student");
	gets(s2.n);
	printf("\n enter the rno");
	scanf("%d", &s2.rno);
	printf("\nenter the marks obtained in physics\n");
	scanf("%d", &s2.m1);
	printf("\nenter the marks obtained in chemistry\n");
	scanf("%d", &s2.m2);
	printf("\nenter the marks obtained in maths\n");
	scanf("%d", &s2.m3);
	printf("\nenter the marks obtained in english\n");
	scanf("%d", &s2.m4);
	printf("\nenter the marks obtained in cs\n");
	scanf("%d", &s2.m5);
	printf("\n enter the name of the student");
	gets(s3.n);
	printf("\n enter the rno");
	scanf("%d", &s3.rno);
	printf("\nenter the marks obtained in physics\n");
	scanf("%d", &s3.m1);
	printf("\nenter the marks obtained in chemistry\n");
	scanf("%d", &s3.m2);
	printf("\nenter the marks obtained in maths\n");
	scanf("%d", &s3.m3);
	printf("\nenter the marks obtained in english\n");
	scanf("%d", &s3.m4);
	printf("\nenter the marks obtained in cs\n");
	scanf("%d", &s3.m5);
	printf("\n enter the name of the student");
	gets(s4.n);
	printf("\n enter the rno");
	scanf("%d", &s4.rno);
	printf("\nenter the marks obtained in physics\n");
	scanf("%d", &s4.m1);
	printf("\nenter the marks obtained in chemistry\n");
	scanf("%d", &s4.m2);
	printf("\nenter the marks obtained in maths\n");
	scanf("%d", &s4.m3);
	printf("\nenter the marks obtained in english\n");
	scanf("%d", &s4.m4);
	printf("\nenter the marks obtained in cs\n");
	scanf("%d", &s4.m5);
	s1.t = s1.m1 + s1.m2 + s1.m3 + s1.m4 + s1.m5;
	s2.t = s2.m1 + s2.m2 + s2.m3 + s2.m4 + s2.m5;
	s3.t = s3.m1 + s3.m2 + s3.m3 + s3.m4 + s3.m5;
	s4.t = s4.m1 + s4.m2 + s4.m3 + s4.m4 + s4.m5;
	s1.a = s1.t / 5;
	s2.a = s2.t / 5;
	s3.a = s3.t / 5;
	s4.a = s4.t / 5;
	s.ac = (s1.a + s2.a + s3.a + s4.a) / 4;
	printf("\n Name\tRollno\tPhysics\tChemistry\tMaths\tCompscie\tTotal\taverage\t Avg of class\n");
	printf("%s", s1.n); printf("\t");
	printf("%d", s1.rno); printf("\t");
	printf("%d", s1.m1); printf("\t");
	printf("%d", s1.m2); printf("\t");
	printf("%d", s1.m3); printf("\t");
	printf("%d", s1.m4); printf("\t");
	printf("%d", s1.t); printf("\t");
	printf("%f", s1.a); printf("\t");
	printf("%f", s.ac);
	printf("\n");
	printf("%s", s2.n); printf("\t");
	printf("%d", s2.rno); printf("\t");
	printf("%d", s2.m1); printf("\t");
	printf("%d", s2.m2); printf("\t");
	printf("%d", s2.m3); printf("\t");
	printf("%d", s2.m4); printf("\t");
	printf("%d", s2.t); printf("\t");
	printf("%f", s2.a); printf("\t");
	printf("%s", s3.n); printf("\t");
	printf("%d", s3.rno); printf("\t");
	printf("%d", s3.m1); printf("\t");
	printf("%d", s3.m2); printf("\t");
	printf("%d", s3.m3); printf("\t");
	printf("%d", s3.m4); printf("\t");
	printf("%d", s3.t); printf("\t");
	printf("%f", s3.a); printf("\t");
	printf("\n");
	printf("%s", s4.n); printf("\t");
	printf("%d", s4.rno); printf("\t");
	printf("%d", s4.m1); printf("\t");
	printf("%d", s4.m2); printf("\t");
	printf("%d", s4.m3); printf("\t");
	printf("%d", s4.m4); printf("\t");
	printf("%d", s4.t); printf("\t");
	printf("%f", s4.a); printf("\t");
	printf("\n");
	getch();
}
struct student
{
	char n[50];
	int rno, m1, m2, m3, m4, m5, t;
	float a, ac;
};